import { hashPassword } from "./auth";
import { DEMO_PASSWORD } from "./demo";
import { RUMILLY } from "./geo";
import type { DB, ScheduleDay } from "./types";

function daysAgo(n: number, hour = 10) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 12, 0, 0);
  return d.toISOString();
}

function weekSchedule(): ScheduleDay[] {
  return [0, 1, 2, 3, 4, 5, 6].map((day) => ({
    day,
    start: "08:00",
    end: "19:00",
    available: day !== 0 && day !== 3,
    breakStart: day !== 0 && day !== 3 ? "12:00" : null,
    breakEnd: day !== 0 && day !== 3 ? "13:00" : null,
  }));
}

function daysFromNow(n: number, hour = 8) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

const planningDefaults = {
  absences: [] as { id: string; startAt: string; endAt: string; reason: "conges" | "maladie" | "formation" | "pause" | "autre"; note?: string }[],
  bufferMinutes: 30,
  leadTimeHours: 2,
  maxMissionsPerDay: 1,
  premiumUntil: null as string | null,
  premiumPlan: "none" as const,
};

export function createSeed(): DB {
  const passwordHash = hashPassword(DEMO_PASSWORD);
  const now = new Date().toISOString();

  const categories = [
    { id: "cat_plomberie", name: "Plomberie", slug: "plomberie", emoji: "🔧", indicativePrice: 59, active: true },
    { id: "cat_electricite", name: "Électricité", slug: "electricite", emoji: "💡", indicativePrice: 65, active: true },
    { id: "cat_serrurerie", name: "Serrurerie", slug: "serrurerie", emoji: "🔑", indicativePrice: 89, active: true },
    { id: "cat_chauffage", name: "Chauffage / clim", slug: "chauffage", emoji: "🌡️", indicativePrice: 79, active: true },
    { id: "cat_peinture", name: "Peinture", slug: "peinture", emoji: "🎨", indicativePrice: 120, active: true },
    { id: "cat_bricolage", name: "Bricolage", slug: "bricolage", emoji: "🛠️", indicativePrice: 45, active: true },
    { id: "cat_maconnerie", name: "Maçonnerie", slug: "maconnerie", emoji: "🧱", indicativePrice: 150, active: true },
    { id: "cat_jardinage", name: "Jardinage", slug: "jardinage", emoji: "🌿", indicativePrice: 55, active: true },
    { id: "cat_menage", name: "Ménage", slug: "menage", emoji: "✨", indicativePrice: 28, active: true },
    { id: "cat_demenagement", name: "Déménagement", slug: "demenagement", emoji: "📦", indicativePrice: 180, active: true },
    { id: "cat_mecanique", name: "Mécanique auto", slug: "mecanique", emoji: "🚗", indicativePrice: 70, active: true },
    { id: "cat_autres", name: "Autres services", slug: "autres", emoji: "➕", indicativePrice: 50, active: true },
  ];

  const users = [
    { id: "usr_admin", role: "admin" as const, email: "admin@appo.fr", passwordHash, firstName: "Léa", lastName: "Moreau", phone: "04 50 00 00 01", avatar: "LM", createdAt: daysAgo(120), suspended: false },
    { id: "usr_sarah", role: "client" as const, email: "sarah@appo.fr", passwordHash, firstName: "Sarah", lastName: "Martin", phone: "06 12 34 56 78", avatar: "SM", createdAt: daysAgo(40), suspended: false },
    { id: "usr_marc", role: "client" as const, email: "marc@appo.fr", passwordHash, firstName: "Marc", lastName: "Dupont", phone: "06 22 33 44 55", avatar: "MD", createdAt: daysAgo(20), suspended: false },
    { id: "usr_kevin", role: "pro" as const, email: "kevin@appo.fr", passwordHash, firstName: "Kevin", lastName: "Petit", phone: "06 45 67 89 01", avatar: "KP", createdAt: daysAgo(90), suspended: false },
    { id: "usr_amina", role: "pro" as const, email: "amina@appo.fr", passwordHash, firstName: "Amina", lastName: "Benali", phone: "06 11 22 33 44", avatar: "AB", createdAt: daysAgo(70), suspended: false },
    { id: "usr_lucas", role: "pro" as const, email: "lucas@appo.fr", passwordHash, firstName: "Lucas", lastName: "Morel", phone: "06 98 76 54 32", avatar: "LM", createdAt: daysAgo(55), suspended: false },
    { id: "usr_chloe", role: "pro" as const, email: "chloe@appo.fr", passwordHash, firstName: "Chloé", lastName: "Roux", phone: "06 55 44 33 22", avatar: "CR", createdAt: daysAgo(48), suspended: false },
    { id: "usr_thomas", role: "pro" as const, email: "thomas@appo.fr", passwordHash, firstName: "Thomas", lastName: "Durand", phone: "06 77 88 99 00", avatar: "TD", createdAt: daysAgo(1), suspended: false },
    { id: "usr_nadia", role: "pro" as const, email: "nadia@appo.fr", passwordHash, firstName: "Nadia", lastName: "Khelifi", phone: "06 14 15 16 17", avatar: "NK", createdAt: daysAgo(30), suspended: false },
    { id: "usr_hugo", role: "pro" as const, email: "hugo@appo.fr", passwordHash, firstName: "Hugo", lastName: "Leroy", phone: "06 18 19 20 21", avatar: "HL", createdAt: daysAgo(25), suspended: false },
  ];

  const addresses = [
    { id: "adr_sarah", userId: "usr_sarah", label: "Domicile", line: "12 rue de la République", city: "Rumilly", zip: "74150", lat: RUMILLY.lat, lng: RUMILLY.lng, isDefault: true },
    { id: "adr_sarah_2", userId: "usr_sarah", label: "Parents", line: "8 avenue d’Annecy", city: "Rumilly", zip: "74150", lat: 45.872, lng: 6.049, isDefault: false },
    { id: "adr_marc", userId: "usr_marc", label: "Maison", line: "4 chemin des Prés", city: "Rumilly", zip: "74150", lat: 45.881, lng: 6.062, isDefault: true },
  ];

  const docsOk = [
    { id: "doc1", type: "identite" as const, name: "CNI.pdf", status: "approved" as const },
    { id: "doc2", type: "entreprise" as const, name: "KBIS.pdf", status: "approved" as const },
    { id: "doc3", type: "assurance" as const, name: "RC_Pro.pdf", status: "approved" as const },
  ];

  const pros = [
    {
      id: "pro_kevin",
      userId: "usr_kevin",
      company: "Plomberie Kevin",
      siret: "839 201 774 00012",
      description: "Plombier à Rumilly depuis 8 ans. Dépannage fuite, débouchage, chauffe-eau et salles de bain. Intervention rapide, devis clair.",
      experienceYears: 8,
      radiusKm: 25,
      lat: 45.8704,
      lng: 6.0498,
      city: "Rumilly",
      online: true,
      verified: true,
      status: "verified" as const,
      startingPrice: 59,
      categoryIds: ["cat_plomberie", "cat_chauffage"],
      photos: [
        "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800",
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
        "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800",
      ],
      certifications: ["Qualibat", "RGE"],
      documents: docsOk,
      schedule: weekSchedule(),
      ...planningDefaults,
      premiumUntil: daysFromNow(60, 23),
      premiumPlan: "monthly" as const,
      rating: 4.9,
      reviewCount: 127,
      missionCount: 37,
      acceptanceRate: 0.92,
    },
    {
      id: "pro_amina",
      userId: "usr_amina",
      company: "Elec Plus",
      siret: "812 445 901 00027",
      description: "Électricienne qualifiée. Tableau électrique, prises, éclairage, dépannage. Travail soigné et aux normes.",
      experienceYears: 6,
      radiusKm: 20,
      lat: 45.8841,
      lng: 6.0712,
      city: "Rumilly",
      online: true,
      verified: true,
      status: "verified" as const,
      startingPrice: 65,
      categoryIds: ["cat_electricite"],
      photos: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800"],
      certifications: ["Qualifelec"],
      documents: docsOk,
      schedule: weekSchedule(),
      ...planningDefaults,
      rating: 4.8,
      reviewCount: 64,
      missionCount: 22,
      acceptanceRate: 0.88,
    },
    {
      id: "pro_lucas",
      userId: "usr_lucas",
      company: "Serrurerie Express",
      siret: "801 992 331 00014",
      description: "Ouverture de porte, changement de cylindre, blindage. Disponible 7j/7 pour les urgences.",
      experienceYears: 11,
      radiusKm: 50,
      lat: 45.899,
      lng: 6.129,
      city: "Annecy",
      online: false,
      verified: true,
      status: "verified" as const,
      startingPrice: 89,
      categoryIds: ["cat_serrurerie"],
      photos: ["https://images.unsplash.com/photo-1558002038-1055907df827?w=800"],
      certifications: ["APSAD"],
      documents: docsOk,
      schedule: weekSchedule().map((d) => ({ ...d, available: d.day !== 0 })),
      ...planningDefaults,
      rating: 4.7,
      reviewCount: 210,
      missionCount: 80,
      acceptanceRate: 0.81,
    },
    {
      id: "pro_chloe",
      userId: "usr_chloe",
      company: "Atelier Roux",
      siret: "844 120 008 00019",
      description: "Peinture intérieure et extérieure, enduits, conseils couleurs. Chantiers soignés.",
      experienceYears: 5,
      radiusKm: 25,
      lat: 45.862,
      lng: 6.041,
      city: "Rumilly",
      online: false,
      verified: true,
      status: "verified" as const,
      startingPrice: 120,
      categoryIds: ["cat_peinture", "cat_bricolage"],
      photos: ["https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800"],
      certifications: [],
      documents: docsOk,
      schedule: weekSchedule(),
      ...planningDefaults,
      absences: [
        {
          id: "abs_chloe",
          startAt: daysFromNow(-1, 0),
          endAt: daysFromNow(7, 23),
          reason: "conges" as const,
          note: "Congés annuels",
        },
      ],
      rating: 4.6,
      reviewCount: 41,
      missionCount: 18,
      acceptanceRate: 0.9,
    },
    {
      id: "pro_thomas",
      userId: "usr_thomas",
      company: "Vert Jardin 74",
      siret: "910 334 221 00008",
      description: "Tonte, taille, haies, petits aménagements extérieurs.",
      experienceYears: 3,
      radiusKm: 15,
      lat: 45.875,
      lng: 6.055,
      city: "Rumilly",
      online: false,
      verified: false,
      status: "pending" as const,
      startingPrice: 55,
      categoryIds: ["cat_jardinage"],
      photos: [],
      certifications: ["Certiphyto"],
      documents: [
        { id: "td1", type: "identite" as const, name: "passeport.pdf", status: "pending" as const },
        { id: "td2", type: "entreprise" as const, name: "kbis.pdf", status: "pending" as const },
        { id: "td3", type: "assurance" as const, name: "rcpro.pdf", status: "pending" as const },
      ],
      schedule: weekSchedule(),
      ...planningDefaults,
      rating: 0,
      reviewCount: 0,
      missionCount: 0,
      acceptanceRate: 1,
    },
    {
      id: "pro_nadia",
      userId: "usr_nadia",
      company: "Nadia Clean",
      siret: "827 110 445 00033",
      description: "Ménage régulier et ponctuel, vitres, remise en état. Matériel fourni.",
      experienceYears: 9,
      radiusKm: 10,
      lat: 45.8795,
      lng: 6.0522,
      city: "Rumilly",
      online: true,
      verified: true,
      status: "verified" as const,
      startingPrice: 28,
      categoryIds: ["cat_menage"],
      photos: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"],
      certifications: [],
      documents: docsOk,
      schedule: weekSchedule(),
      ...planningDefaults,
      rating: 4.9,
      reviewCount: 96,
      missionCount: 54,
      acceptanceRate: 0.95,
    },
    {
      id: "pro_hugo",
      userId: "usr_hugo",
      company: "Clim & Chauffage Leroy",
      siret: "753 882 190 00041",
      description: "Entretien chaudière, clim, pompes à chaleur. Dépannage du jour même.",
      experienceYears: 14,
      radiusKm: 25,
      lat: 45.868,
      lng: 6.066,
      city: "Rumilly",
      online: true,
      verified: true,
      status: "verified" as const,
      startingPrice: 79,
      categoryIds: ["cat_chauffage"],
      photos: ["https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800"],
      certifications: ["RGE QualiPAC", "PG"],
      documents: docsOk,
      schedule: weekSchedule(),
      ...planningDefaults,
      rating: 4.8,
      reviewCount: 73,
      missionCount: 29,
      acceptanceRate: 0.87,
    },
  ];

  const missions = [
    {
      id: "mis_done_1",
      type: "now" as const,
      clientId: "usr_sarah",
      proId: "pro_kevin",
      categoryId: "cat_plomberie",
      status: "completed" as const,
      address: "12 rue de la République",
      city: "Rumilly",
      lat: RUMILLY.lat,
      lng: RUMILLY.lng,
      description: "Fuite sous évier cuisine",
      photos: [],
      scheduledAt: null,
      price: 89,
      supplement: 0,
      pendingSupplement: null,
      pendingSupplementReason: null,
      commissionRate: 0.15,
      createdAt: daysAgo(0, 9),
      timeline: [
        { status: "accepted", at: daysAgo(0, 9), label: "Mission confirmée" },
        { status: "completed", at: daysAgo(0, 11), label: "Intervention terminée" },
      ],
      candidateProIds: [],
      declinedProIds: [],
      offerProId: null,
      offerExpiresAt: null,
      etaMinutes: null,
      startProLat: null,
      startProLng: null,
      paymentStatus: "paid" as const,
      paymentMethod: "card",
    },
    {
      id: "mis_done_2",
      type: "scheduled" as const,
      clientId: "usr_marc",
      proId: "pro_kevin",
      categoryId: "cat_plomberie",
      status: "completed" as const,
      address: "4 chemin des Prés",
      city: "Rumilly",
      lat: 45.881,
      lng: 6.062,
      description: "Remplacement mitigeur salle de bain",
      photos: [],
      scheduledAt: daysAgo(2, 14),
      price: 140,
      supplement: 40,
      pendingSupplement: null,
      pendingSupplementReason: null,
      commissionRate: 0.15,
      createdAt: daysAgo(3, 18),
      timeline: [
        { status: "accepted", at: daysAgo(3, 18), label: "Mission confirmée" },
        { status: "completed", at: daysAgo(2, 16), label: "Intervention terminée" },
      ],
      candidateProIds: [],
      declinedProIds: [],
      offerProId: null,
      offerExpiresAt: null,
      etaMinutes: null,
      startProLat: null,
      startProLng: null,
      paymentStatus: "paid" as const,
      paymentMethod: "apple_pay",
    },
    {
      id: "mis_month_1",
      type: "now" as const,
      clientId: "usr_marc",
      proId: "pro_kevin",
      categoryId: "cat_chauffage",
      status: "completed" as const,
      address: "4 chemin des Prés",
      city: "Rumilly",
      lat: 45.881,
      lng: 6.062,
      description: "Purge radiateurs",
      photos: [],
      scheduledAt: null,
      price: 95,
      supplement: 0,
      pendingSupplement: null,
      pendingSupplementReason: null,
      commissionRate: 0.15,
      createdAt: daysAgo(8, 10),
      timeline: [{ status: "completed", at: daysAgo(8, 12), label: "Intervention terminée" }],
      candidateProIds: [],
      declinedProIds: [],
      offerProId: null,
      offerExpiresAt: null,
      etaMinutes: null,
      startProLat: null,
      startProLng: null,
      paymentStatus: "paid" as const,
      paymentMethod: "card",
    },
    {
      id: "mis_planned",
      type: "scheduled" as const,
      clientId: "usr_sarah",
      proId: "pro_chloe",
      categoryId: "cat_peinture",
      status: "accepted" as const,
      address: "12 rue de la République",
      city: "Rumilly",
      lat: RUMILLY.lat,
      lng: RUMILLY.lng,
      description: "Peinture chambre 12m², blanc cassé",
      photos: [],
      scheduledAt: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
      price: 180,
      supplement: 0,
      pendingSupplement: null,
      pendingSupplementReason: null,
      commissionRate: 0.15,
      createdAt: daysAgo(1, 16),
      timeline: [{ status: "accepted", at: daysAgo(1, 16), label: "Mission confirmée" }],
      candidateProIds: [],
      declinedProIds: [],
      offerProId: null,
      offerExpiresAt: null,
      etaMinutes: null,
      startProLat: null,
      startProLng: null,
      paymentStatus: "none" as const,
      paymentMethod: null,
    },
    {
      id: "mis_dispute",
      type: "now" as const,
      clientId: "usr_marc",
      proId: "pro_lucas",
      categoryId: "cat_serrurerie",
      status: "disputed" as const,
      address: "4 chemin des Prés",
      city: "Rumilly",
      lat: 45.881,
      lng: 6.062,
      description: "Porte claquée, clé à l’intérieur",
      photos: [],
      scheduledAt: null,
      price: 129,
      supplement: 0,
      pendingSupplement: null,
      pendingSupplementReason: null,
      commissionRate: 0.15,
      createdAt: daysAgo(5, 21),
      timeline: [
        { status: "completed", at: daysAgo(5, 22), label: "Intervention terminée" },
        { status: "disputed", at: daysAgo(4, 9), label: "Litige ouvert" },
      ],
      candidateProIds: [],
      declinedProIds: [],
      offerProId: null,
      offerExpiresAt: null,
      etaMinutes: null,
      startProLng: null,
      startProLat: null,
      paymentStatus: "paid" as const,
      paymentMethod: "card",
    },
  ];

  const pay = (id: string, missionId: string, amount: number, method: string, createdAt: string) => {
    const commission = Math.round(amount * 0.15 * 100) / 100;
    return {
      id,
      missionId,
      amount,
      commission,
      proAmount: Math.round((amount - commission) * 100) / 100,
      status: "paid" as const,
      method,
      createdAt,
      paidAt: createdAt,
    };
  };

  const extraToday = [
    pay("pay_t1", "mis_extra_1", 120, "card", daysAgo(0, 8)),
    pay("pay_t2", "mis_extra_2", 160, "google_pay", daysAgo(0, 13)),
    pay("pay_t3", "mis_extra_3", 95, "card", daysAgo(0, 15)),
  ];

  const extraMissions = extraToday.map((p, i) => ({
    id: p.missionId,
    type: "now" as const,
    clientId: "usr_marc",
    proId: "pro_kevin",
    categoryId: "cat_plomberie",
    status: "completed" as const,
    address: "4 chemin des Prés",
    city: "Rumilly",
    lat: 45.881,
    lng: 6.062,
    description: ["Débouchage évier", "Joint robinet", "Flexible douche"][i],
    photos: [],
    scheduledAt: null,
    price: p.amount,
    supplement: 0,
    pendingSupplement: null,
    pendingSupplementReason: null,
    commissionRate: 0.15,
    createdAt: p.createdAt,
    timeline: [{ status: "completed", at: p.createdAt, label: "Intervention terminée" }],
    candidateProIds: [],
    declinedProIds: [],
    offerProId: null,
    offerExpiresAt: null,
    etaMinutes: null,
    startProLat: null,
    startProLng: null,
    paymentStatus: "paid" as const,
    paymentMethod: p.method,
  }));

  const extraMonth = [210, 175, 240, 130, 190, 155, 200, 110, 145].map((amount, i) =>
    pay(`pay_m${i}`, `mis_m_${i}`, amount, "card", daysAgo(6 + i, 11)),
  );

  const extraMonthMissions = extraMonth.map((p, i) => ({
    id: p.missionId,
    type: "now" as const,
    clientId: i % 2 === 0 ? "usr_sarah" : "usr_marc",
    proId: "pro_kevin",
    categoryId: "cat_plomberie",
    status: "completed" as const,
    address: "Rumilly",
    city: "Rumilly",
    lat: RUMILLY.lat,
    lng: RUMILLY.lng,
    description: "Intervention plomberie",
    photos: [],
    scheduledAt: null,
    price: p.amount,
    supplement: 0,
    pendingSupplement: null,
    pendingSupplementReason: null,
    commissionRate: 0.15,
    createdAt: p.createdAt,
    timeline: [{ status: "completed", at: p.createdAt, label: "Intervention terminée" }],
    candidateProIds: [],
    declinedProIds: [],
    offerProId: null,
    offerExpiresAt: null,
    etaMinutes: null,
    startProLat: null,
    startProLng: null,
    paymentStatus: "paid" as const,
    paymentMethod: "card",
  }));

  return {
    users,
    addresses,
    categories,
    pros,
    missions: [...missions, ...extraMissions, ...extraMonthMissions],
    messages: [
      {
        id: "msg1",
        missionId: "mis_planned",
        senderId: "usr_sarah",
        text: "Le mur est actuellement beige clair. Merci !",
        createdAt: daysAgo(1, 16),
      },
      {
        id: "msg2",
        missionId: "mis_planned",
        senderId: "usr_chloe",
        text: "Parfait, je passe avec deux couches de blanc cassé.",
        createdAt: daysAgo(1, 17),
      },
    ],
    reviews: [
      {
        id: "rev1",
        missionId: "mis_done_1",
        clientId: "usr_sarah",
        proId: "pro_kevin",
        rating: 5,
        comment: "Très professionnel, rapide et efficace.",
        photos: [],
        createdAt: daysAgo(0, 12),
      },
      {
        id: "rev2",
        missionId: "mis_done_2",
        clientId: "usr_marc",
        proId: "pro_kevin",
        rating: 5,
        comment: "A tout expliqué, chantier nickel.",
        photos: [],
        createdAt: daysAgo(2, 17),
      },
    ],
    payments: [
      pay("pay1", "mis_done_1", 89, "card", daysAgo(0, 11)),
      pay("pay2", "mis_done_2", 180, "apple_pay", daysAgo(2, 16)),
      pay("pay3", "mis_month_1", 95, "card", daysAgo(8, 12)),
      pay("pay4", "mis_dispute", 129, "card", daysAgo(5, 22)),
      ...extraToday,
      ...extraMonth,
    ],
    notifications: [
      {
        id: "n1",
        userId: "usr_sarah",
        title: "Intervention terminée",
        body: "Kevin a terminé l’intervention — 89 €",
        read: true,
        href: "/app/missions/mis_done_1",
        createdAt: daysAgo(0, 11),
      },
      {
        id: "n2",
        userId: "usr_admin",
        title: "Nouveau professionnel à valider",
        body: "Thomas Durand — Vert Jardin 74",
        read: false,
        href: "/admin/pros",
        createdAt: daysAgo(1, 9),
      },
    ],
    favorites: [{ clientId: "usr_sarah", proId: "pro_kevin" }],
    disputes: [
      {
        id: "dsp1",
        missionId: "mis_dispute",
        openedBy: "usr_marc",
        reason: "Cylindre changé sans accord, facture trop élevée.",
        status: "open",
        createdAt: daysAgo(4, 9),
      },
    ],
    settings: {
      commissionRate: 0.15,
      offerSeconds: 20,
      premiumMonthlyPrice: 49,
      premiumYearlyPrice: 399,
      premiumExclusiveSeconds: 45,
      premiumOfferBonusSeconds: 10,
    },
  };
}

